In [7]:
#4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# 2. Initialize an all one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
full_array = np.full((3, 3), 7)   
print("\nFull Array (3x3 filled with 7):\n", full_array)

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Like Array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\nOnes Like Array:\n", ones_like_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted Numpy Array:\n", numpy_array)

Empty Array (2x2):
 [[-2.    1.  ]
 [ 1.75 -0.75]]

All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full Array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
 [[0 0]
 [0 0]]

Ones Like Array:
 [[1 1]
 [1 1]]

Converted Numpy Array:
 [1 2 3 4]


In [2]:
#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("Array from 10 to 49:\n", arr1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix (0 to 8):\n", arr2)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\nIdentity Matrix (3x3):\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array (size 30):\n", random_array)
print("Mean of Random Array:", mean_value)

# 5. Create a 10x10 array with random values and find min and max
random_matrix = np.random.random((10, 10))
min_val, max_val = random_matrix.min(), random_matrix.max()
print("\n10x10 Random Matrix:\n", random_matrix)
print("Minimum Value:", min_val)
print("Maximum Value:", max_val)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1   # index 4 = 5th element
print("\nZero Array with 5th element replaced:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))   # example size 5x5
border_array[1:-1, 1:-1] = 0
print("\n2D Array with Border 1 and Inside 0:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array (size 30):
 [0.4944936  0.72525882 0.54471187 0.71705483 0.45080418 0.28100076
 0.70306248 0.29020972 0.26235024 0.38441498 0.04619935 0.68869586
 0.1091076  0.93629998 0.01116857 0.36091535 0.08206855 0.26721752
 0.88046495 0.53978766 0.59480532 0.28146183 0.30175082 0.61820555
 0.93484641 0.06146556 0.53646867 0.6978109  0.40840656 0.98192984]
Mean of Random Array: 0.4730812770047244

10x10 Random Matrix:
 [[0.20196815 0.76967461 0.68926422 0.4171798  0.93535918 0.84975092
  0.81585272 0.9712227  0.51598995 0.23950546]
 [0.14151028 0.60620966 0.29536261 0.65161658 0.03412488 0.69450758
  0.65725957 0.83894959 0.41889835 0.50163881]
 [0.4711233  0.72702616 0.90929312 0.2844691  0.23035704 0.41043366
  0.73649127 0.520

In [3]:
#Problem - 3: Array Operations:

import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nSubtraction of x and y:\n", sub_xy)

# 3. Multiply the array with any integer (example: multiply x by 3)
mult_x = x * 3
print("\nMultiplication of x by 3:\n", mult_x)

# 4. Find the square of each element of the array (example: square of x)
square_x = np.square(x)
print("\nSquare of each element in x:\n", square_x)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product v·w:", dot_vw)
print("Dot product x·v:\n", dot_xv)
print("Dot product x·y:\n", dot_xy)

# 6. Concatenate x and y along rows
concat_xy_rows = np.concatenate((x, y), axis=0)
print("\nConcatenate x and y along rows:\n", concat_xy_rows)

# Concatenate v and w along columns (stack vertically then transpose)
concat_vw_cols = np.vstack((v, w)).T
print("\nConcatenate v and w along columns:\n", concat_vw_cols)



Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product v·w: 219
Dot product x·v:
 [29 77]
Dot product x·y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


In [4]:
#PROBLEM 4 

import numpy as np

# Define matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)          
identity = np.dot(A, A_inv)       
print("A * A^-1:\n", identity)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)
print("Is AB equal to BA?", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n(AB)^T:\n", AB_T)
print("B^T A^T:\n", BT_AT)
print("Are they equal?", np.array_equal(AB_T, BT_AT))

A * A^-1:
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Are they equal? True


In [5]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

# Constants vector b
b = np.array([-1, -3, 9])

# Solve using inverse method: x = A^-1 * b
A_inv = np.linalg.inv(A)
solution = np.dot(A_inv, b)

print("Solution (x, y, z):", solution)

Solution (x, y, z): [ 2.  1. -2.]


In [6]:
#USING LINALG
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

# Constants vector b
b = np.array([-1, -3, 9])

# Solve using inverse method: x = A^-1 * b
A_inv = np.linalg.inv(A)          
solution = np.dot(A_inv, b)       

print("Solution (x, y, z):", solution)

Solution (x, y, z): [ 2.  1. -2.]
